image:
  repository: postgres
  tag: "16-alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432

env:
  POSTGRES_USER: "ngen"
  POSTGRES_PASSWORD: "ngen_dev_password"
  POSTGRES_DB: "ngen"

storage:
  size: 1Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
